### ISSUE TITLE
MG1 Issues

### ISSUE THREAD

**Issue by cynlik** [MestroGroup/mgTimer-Public#56]
upon loading new map massive lag happens as before in 1.7 but seems to be worse; 
wrcps and SRs seem to not load as well as player info;
ranks get swapped and are completely wrong; 
most commands also don't work during this time; 
server enters into an unconfigured state where players can kill eachother;

**Comment by cynlik** [comment]
glass sound persists;
bots seem to still be broken for the most part;
bot time doesn't coincide with SR time shown on !maptop and user UI;
pre strafe speed seems to be higher (check server settings?);

ENHANCEMENT: maybe set map finish, CP messages and all messages regarding rank/speed/time to have more contrast and maybe change colours depending where its from another user or my own;

remove glass shatter sound (community suggestion);

**Comment by cynlik** [comment]
total number of stages shown in !srcp does not coincide with total amount of stages on map (at least for surf_mom);
last stage still seems to not show on !srcp -- says there are no records for that stage (at least for surf_mom);

**Comment by MestroGroup** [comment]
Anything else then make another bug report. I'll decant this one after work.

**Comment by MestroGroup** [comment]
**Loading New Map Lag**
Queue system implemented;
server will now load 5 players at any one time and no more. Various optimizations also added to the server loading process.

**WRCPs and SRs not loading**
Should now be resolved - Further detail will be required in a separate bug report if issues persist.

**Ranks get swapped**
Should now be resolved - Further detail will be required in a separate bug report if issues persist.

**Most commands don't work during this time**
Commands will not operate until players have loaded - Further detail will be required in a separate bug report if issues persist. 

**Glass sound persists**
This is not a bug, working as intended.

**Bot seems to be broken for the most part**
This is not enough information for me to do anything with, all seems to work as intended in the development environment.

**Bot time doesn't coinside with SR**
This would be because the recording of the SR is no longer available,
reasons include;
- Replay was buggy and replaced
- Previous SR was removed and the bot was not reset (I can remove in this case)

**Pre-strafe speed seems higher**
Pre-strafe speed as selected in /options will show XYZ velocity as opposed to XY.
If XY only is preferred, please open a new enhancement.

**WRCP Issues**
I've been unable to produce this on the development environment after many attempts.
The issue may be resolved, please verify and open a new report if the issue persists.
